name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        build_type: [Release, Debug]
        cpp_compiler: [g++, clang++]
        enable_asan: [0, 1]
        enable_ubsan: [0, 1]
        exclude:
          - os: macos-latest
            cpp_compiler: g++
          - enable_asan: 1
            enable_ubsan: 1
          - build_type: Release
            enable_asan: 1
          - build_type: Release
            enable_ubsan: 1

    steps:
    - uses: actions/checkout@v3

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DENABLE_ASAN=${{ matrix.enable_asan }}
        -DENABLE_UBSAN=${{ matrix.enable_ubsan }}
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Run tests
      if: matrix.os != 'windows-latest'
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ./tests
